"""tambah keterangan di alat_log

Revision ID: 282e5da135eb
Revises: e42e5d79e6f7
Create Date: 2025-11-10 14:06:19.793501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282e5da135eb'
down_revision: Union[str, Sequence[str], None] = 'e42e5d79e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alat_log', sa.Column('keterangan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alat_log', 'keterangan')
    # ### end Alembic commands ###
