"""initial migration

Revision ID: 55b294ad43a9
Revises: 
Create Date: 2025-11-10 12:49:30.552775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b294ad43a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.Column('tanggal_input', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alat_id'), 'alat', ['id'], unique=False)
    op.create_table('dokter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('spesialis', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telp', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dokter_id'), 'dokter', ['id'], unique=False)
    op.create_table('pasien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('telp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasien_id'), 'pasien', ['id'], unique=False)
    op.create_table('rekam_medis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasien_id', sa.Integer(), nullable=True),
    sa.Column('dokter_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('keluhan', sa.String(), nullable=True),
    sa.Column('diagnosa', sa.String(), nullable=True),
    sa.Column('tindakan', sa.String(), nullable=True),
    sa.Column('biaya_tindakan', sa.Integer(), nullable=True),
    sa.Column('biaya_bahan', sa.Integer(), nullable=True),
    sa.Column('biaya_obat', sa.Integer(), nullable=True),
    sa.Column('total_biaya', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dokter_id'], ['dokter.id'], ),
    sa.ForeignKeyConstraint(['pasien_id'], ['pasien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rekam_medis_id'), 'rekam_medis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rekam_medis_id'), table_name='rekam_medis')
    op.drop_table('rekam_medis')
    op.drop_index(op.f('ix_pasien_id'), table_name='pasien')
    op.drop_table('pasien')
    op.drop_index(op.f('ix_dokter_id'), table_name='dokter')
    op.drop_table('dokter')
    op.drop_index(op.f('ix_alat_id'), table_name='alat')
    op.drop_table('alat')
    # ### end Alembic commands ###
