"""tambah kolom tanggal di tabel alat

Revision ID: 7c52d0dc4320
Revises: 2ad87515f76c
Create Date: 2025-11-10 13:12:34.243841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c52d0dc4320'
down_revision: Union[str, Sequence[str], None] = '2ad87515f76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alat', sa.Column('tanggal', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alat', 'tanggal')
    # ### end Alembic commands ###
