"""add total_biaya to rekam_medis

Revision ID: d767956b044b
Revises: f85cffa65e7d
Create Date: 2025-10-26 18:44:21.400787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd767956b044b'
down_revision: Union[str, Sequence[str], None] = 'f85cffa65e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rekam_medis', sa.Column('total_biaya', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rekam_medis', 'total_biaya')
    # ### end Alembic commands ###
