"""tambah tabel alat_log

Revision ID: e42e5d79e6f7
Revises: 7c52d0dc4320
Create Date: 2025-11-10 13:38:41.322552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42e5d79e6f7'
down_revision: Union[str, Sequence[str], None] = '7c52d0dc4320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('nama_alat', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('harga_satuan', sa.Integer(), nullable=True),
    sa.Column('total_nilai', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alat_log_id'), 'alat_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alat_log_id'), table_name='alat_log')
    op.drop_table('alat_log')
    # ### end Alembic commands ###
