"""Initial migration

Revision ID: f85cffa65e7d
Revises: 
Create Date: 2025-08-07 12:36:31.129596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85cffa65e7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rekam_medis', sa.Column('biaya_bahan', sa.Integer(), nullable=True))
    op.drop_column('rekam_medis', 'biaya_dokter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rekam_medis', sa.Column('biaya_dokter', sa.INTEGER(), nullable=True))
    op.drop_column('rekam_medis', 'biaya_bahan')
    # ### end Alembic commands ###
